#%RAML 1.0 SecurityScheme
type: x-token-authorize
description: This will make sure that we have client_id and client_secret in Authorization header
describedBy:
  headers:
    client_id:
      type: string
    client_secret:
      type: string
  responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error