#%RAML 1.0 Library
types:
  getcustomerResponse:
    displayName: getcustomerResponse
    properties: 
      sfdcAddressId:
        type: string
        required: false
      netsuiteAddressId:
        type: string
        required: false

  getsalesOrderResponse:
    displayName: getsalesOrderResponse
    properties:
      orderInternalId:
        type: string
        required: false
      orderTranId:
        type: string
        required: false
